name: Generate images.json

on:
  push:
    paths:
      - 'img/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate images.json with folders and cover
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');

          function scanDir(dir) {
            const items = [];
            fs.readdirSync(dir).forEach(file => {
              const fullPath = path.join(dir, file);
              const relPath = fullPath.replace(/\\/g, '/');
              if (fs.statSync(fullPath).isDirectory()) {
                const children = scanDir(fullPath);
                if (children.length > 0) {
                  items.push({
                    type: 'folder',
                    title: file,
                    cover: children.find(i => i.type==='image')?.url || '',
                    children: children
                  });
                }
              } else if (/\.(jpg|jpeg|png|gif)$/i.test(file)) {
                items.push({
                  type: 'image',
                  title: file,
                  url: 'https://raw.githubusercontent.com/ggku2021/r2-album/main/' + relPath
                });
              }
            });
            return items;
          }

          const result = scanDir('img');
          fs.writeFileSync('images.json', JSON.stringify(result, null, 2));
          console.log('images.json generated with', result.length, 'items');
          "

      - name: Commit and push images.json
        run: |
          git config user.name "ggku2021"
          git config user.email "ggku@qq.com"
          git add images.json
          git commit -m '自动生成 images.json' || echo 'No changes to commit'
          git push origin main
