name: Generate images.json

on:
  push:
    paths:
      - 'img/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate images.json recursively
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');

          function getImages(dir) {
            let results = [];
            fs.readdirSync(dir).forEach(file => {
              const fullPath = path.join(dir, file);
              const stat = fs.statSync(fullPath);
              if (stat && stat.isDirectory()) {
                results = results.concat(getImages(fullPath)); // 递归扫描子文件夹
              } else if (/\.(jpg|jpeg|png|gif)$/i.test(file)) {
                results.push({
                  filename: file,
                  url: 'https://raw.githubusercontent.com/ggku2021/r2-album/main/' + fullPath.replace(/\\/g,'/'),
                  title: file
                });
              }
            });
            return results;
          }

          const images = getImages('img');
          fs.writeFileSync('images.json', JSON.stringify(images, null, 2));
          console.log('images.json generated with', images.length, 'images');
          "

      - name: Commit and push images.json
        run: |
          git config user.name "ggku2021"
          git config user.email "ggku@qq.com"
          git add images.json
          git commit -m '自动生成 images.json' || echo 'No changes to commit'
          git push origin main
