name: Generate images.json from img folder

on:
  push:
    paths:
      - 'img/**'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate images.json
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const path = 'img';
          const repo = process.env.GITHUB_REPOSITORY;
          const branch = process.env.GITHUB_REF.replace('refs/heads/', '');
          
          if (!fs.existsSync(path)) {
            console.log('img folder does not exist.');
            process.exit(0);
          }

          const files = fs.readdirSync(path).filter(f => !f.startsWith('.') && !f.startsWith('_'));
          const items = files.map(f => ({
            filename: f,
            url: `https://cdn.jsdelivr.net/gh/${repo}@${branch}/img/${encodeURIComponent(f)}`,
            title: f
          }));

          fs.writeFileSync('images.json', JSON.stringify(items, null, 2));
          console.log(`Generated images.json with ${items.length} items`);
          NODE

      - name: Commit & push images.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add images.json
          git diff --staged --quiet || (git commit -m "chore: update images.json" && git push)
