name: Generate images.json

on:
  push:
    paths:
      - 'img/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate images.json with folders and cover
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');

          function getFoldersImages(dir) {
            let folders = [];
            fs.readdirSync(dir).forEach(folderName => {
              const folderPath = path.join(dir, folderName);
              if (fs.statSync(folderPath).isDirectory()) {
                const images = [];
                fs.readdirSync(folderPath).forEach(file => {
                  if (/\.(jpg|jpeg|png|gif)$/i.test(file)) {
                    images.push({
                      filename: file,
                      url: 'https://raw.githubusercontent.com/ggku2021/r2-album/main/' + path.join(folderPath, file).replace(/\\/g,'/'),
                      title: file
                    });
                  }
                });
                if (images.length > 0) {
                  folders.push({
                    folder: folderName,
                    cover: images[0].url,
                    images: images
                  });
                }
              }
            });
            return folders;
          }

          const result = getFoldersImages('img');
          fs.writeFileSync('images.json', JSON.stringify(result, null, 2));
          console.log('images.json generated with', result.length, 'folders');
          "

      - name: Commit and push images.json
        run: |
          git config user.name "ggku2021"
          git config user.email "ggku@qq.com"
          git add images.json
          git commit -m '自动生成 images.json' || echo 'No changes to commit'
          git push origin main
